### ISSUE TITLE
What are significant differences from FactoryGirl?

### ISSUE THREAD

**Issue by algimantas** [andriusch/blueprints_boy#1]
In what ways BlueprintsBoy is significantly better than [FactoryGirl](https://github.com/thoughtbot/factory_girl/)?
In which cases, people should consider switching from FactoryGirl to BlueprintsBoy?

**Comment by andriusch** [comment]
It all depends on your definition of significant, but IMO these are:

1. Isn't built around ORM, so makes it easy to integrate with various types of objects (plain Ruby, exotic ORM, etc.)
2. Convention over configuration. It automatically setups DatabaseCleaner for example, doesn't require any generators to get started and it's only going to get better.
3. Focused on building scenarios not objects. Sure most of the time you will be building objects in your scenarios, but sometimes you need HTTP mock with webmock for example and BlueprintsBoy makes it easy to do.
4. Focused on being DRY without sacrificing clarity. I think that's the issue with FactoryGirl it's either not DRY enough or if you try to be DRY it loses clarity.

Are these significant or not depends on your definition of significant, but even if it's not significant enough to migrate your current project, I think BlueprintsBoy is the better option for a new project.
